# Generated by Django 5.0 on 2023-12-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccountprofile',
            name='account_number',
        ),
    ]
