# Generated by Django 5.0 on 2023-12-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0003_alter_customeraccountprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=60, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customeraccountprofile')),
            ],
        ),
    ]
