# Generated by Django 5.0 on 2023-12-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0003_transfer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='Accountapp.accountdetails'),
        ),
    ]
