# Generated by Django 5.0 on 2023-12-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0005_alter_transfer_receiver_alter_transfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, choices=[('AIRTEL', 'AIRTEL'), ('9MOBILE', '9MOBILE'), ('MTN', 'MTN'), ('GLO', 'GLO')], max_length=10, null=True)),
                ('receiver', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='PENDING', max_length=60, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime', to='Accountapp.accountdetails')),
            ],
        ),
    ]
