# Generated by Django 5.0 on 2023-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0006_airtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='receiver',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
