# Generated by Django 5.0 on 2023-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0007_alter_airtime_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
