# Generated by Django 5.0 on 2023-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0008_alter_accountdetails_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
