# Generated by Django 5.0 on 2023-12-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0009_alter_accountdetails_account_balance'),
        ('Customer', '0003_alter_customeraccountprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='Customer.customeraccountprofile'),
        ),
    ]
