# Generated by Django 5.0 on 2023-12-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0010_alter_accountdetails_account_owner'),
        ('Customer', '0003_alter_customeraccountprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customeraccountprofile'),
        ),
    ]
